<?php
/**
 * Created by PhpStorm.
 * User: edxxu
 * Date: 12/17/15
 * Time: 8:15 PM
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function theme_suggestion_demo_theme_suggestions_select_alter(array &$suggestions, array $variables) {
  $routeObject = \Drupal::routeMatch()->getRouteObject();
  $view_id = $routeObject->getDefault('view_id');
  $display_id = $routeObject->getDefault('display_id');

  if (!empty($view_id)) {
    $suggestions[] = 'select__' . $view_id;

    if (!empty($display_id)) {
      $suggestions[] = 'select__' . $view_id . '_' . $display_id;
    }
  }
}